#!/usr/bin/env python3
"""
DogPhone setup web server – runs when device has no config.
Serves wizard UI with QR code; collects WiFi (optional) and Telegram; writes config.
"""
import json
import logging
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import load_config

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("setup")

try:
    from flask import Flask, request, jsonify, send_from_directory
    HAS_FLASK = True
except ImportError:
    HAS_FLASK = False
    Flask = None

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = REPO_ROOT / "config" / "config.env"
SETUP_HTML = Path(__file__).resolve().parent / "setup_wizard.html"

# Default AP IP when Pi is in hotspot mode (create_ap / typical hostapd)
SETUP_AP_IP = "192.168.4.1"


def get_setup_url() -> str:
    """URL the phone should open: prefer this machine's IP on port 8765."""
    port = load_config().get("setup_port", 8765)
    try:
        import socket
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(0)
        s.connect(("192.168.4.1", 1))
        ip = s.getsockname()[0]
        s.close()
    except Exception:
        ip = SETUP_AP_IP
    return f"http://{ip}:{port}"


def write_config(updates: dict) -> None:
    """Merge updates into config.env (create file if missing)."""
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    existing = {}
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            for line in f:
                m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line.strip())
                if m:
                    existing[m.group(1)] = m.group(2).strip()
    for k, v in updates.items():
        if v is not None and str(v).strip():
            existing[k] = str(v).strip()
    with open(CONFIG_FILE, "w") as f:
        f.write("# DogPhone – generated by setup\n")
        for k, v in sorted(existing.items()):
            f.write(f"{k}={v}\n")
    log.info("Wrote config: %s", CONFIG_FILE)


def fetch_chat_id(token: str) -> str | None:
    """Get latest chat id from Telegram getUpdates."""
    try:
        import requests
        r = requests.get(
            f"https://api.telegram.org/bot{token}/getUpdates",
            timeout=10,
        )
        r.raise_for_status()
        data = r.json()
        if not data.get("ok"):
            return None
        for u in reversed(data.get("result", [])):
            msg = u.get("message") or u.get("edited_message")
            if msg and "chat" in msg:
                return str(msg["chat"]["id"])
    except Exception as e:
        log.warning("getUpdates failed: %s", e)
    return None


def connect_wifi(ssid: str, password: str) -> bool:
    """Try to connect Pi to WiFi using nmcli (Raspberry Pi OS Bookworm)."""
    if not ssid or not ssid.strip():
        return False
    try:
        subprocess.run(
            [
                "nmcli", "device", "wifi", "connect",
                ssid.strip(),
                "password", password,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return True
    except Exception as e:
        log.warning("nmcli connect failed: %s", e)
    return False


def create_app():
    app = Flask(__name__)

    @app.route("/")
    def index():
        return send_setup_html()

    @app.route("/setup")
    def setup():
        return send_setup_html()

    def send_setup_html():
        if SETUP_HTML.exists():
            return send_from_directory(SETUP_HTML.parent, SETUP_HTML.name)
        return "<h1>Setup</h1><p>Place setup_wizard.html in the pi/ folder.</p>", 404

    @app.route("/api/status")
    def api_status():
        cfg = load_config()
        setup_url = get_setup_url()
        return jsonify({
            "setup_url": setup_url,
            "has_token": bool(cfg.get("telegram_bot_token")),
            "chat_id": cfg.get("telegram_chat_id") or "",
            "ready": bool(cfg.get("telegram_bot_token") and cfg.get("telegram_chat_id")),
        })

    @app.route("/api/telegram", methods=["POST"])
    def api_telegram():
        data = request.get_json() or {}
        token = (data.get("token") or "").strip()
        if not token:
            return jsonify({"ok": False, "error": "Token required"}), 400
        write_config({"TELEGRAM_BOT_TOKEN": token})
        return jsonify({"ok": True})

    @app.route("/api/chat_id")
    def api_chat_id():
        cfg = load_config()
        token = cfg.get("telegram_bot_token")
        if not token:
            return jsonify({"ok": False, "chat_id": None})
        cid = fetch_chat_id(token)
        if cid:
            write_config({"TELEGRAM_CHAT_ID": cid})
            return jsonify({"ok": True, "chat_id": cid})
        return jsonify({"ok": False, "chat_id": None})

    @app.route("/api/wifi", methods=["POST"])
    def api_wifi():
        data = request.get_json() or {}
        ssid = (data.get("ssid") or "").strip()
        password = (data.get("password") or "")
        if not ssid:
            return jsonify({"ok": False, "error": "WiFi name required"}), 400
        if connect_wifi(ssid, password):
            return jsonify({"ok": True})
        return jsonify({"ok": False, "error": "Could not connect. Check password and try again."}), 400

    @app.route("/api/complete", methods=["POST"])
    def api_complete():
        data = request.get_json() or {}
        cid = (data.get("chat_id") or "").strip()
        if cid:
            write_config({"TELEGRAM_CHAT_ID": cid})
        # Reboot so device starts in normal (main app) mode
        try:
            subprocess.Popen(
                ["sudo", "reboot"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception:
            pass
        return jsonify({"ok": True, "reboot": True})

    return app


def main():
    if not HAS_FLASK:
        log.error("Install Flask: pip install flask")
        sys.exit(1)
    cfg = load_config()
    port = cfg.get("setup_port", 8765)
    url = get_setup_url()
    log.info("Setup server at %s", url)
    create_app().run(host="0.0.0.0", port=port, debug=False, threaded=True)


if __name__ == "__main__":
    main()
